sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - REQUIREMENTS=django-16
  - REQUIREMENTS=django-17
  - REQUIREMENTS=django-18
  - REQUIREMENTS=django-master

matrix:
  allow_failures:
    - env: REQUIREMENTS=django-master
  exclude:
    # Django >= 1.7 does not support Python 2.6
    - python: "2.6"
      env: REQUIREMENTS=django-17
    - python: "2.6"
      env: REQUIREMENTS=django-18
    - python: "2.6"
      env: REQUIREMENTS=django-master
    # Django >= 1.8 does not support Python 3.2 and 3.3
    - python: "3.2"
      env: REQUIREMENTS=django-master
    - python: "3.3"
      env: REQUIREMENTS=django-master

install:
  - pip install tox

script:
  - tox -e py-$REQUIREMENTS
